ROADMAP.md
Signed-off-by: noah <iamnoah@gmail.com>
=> remove extraneous trailing \ (breaking link)

GOVERNANCE.md
Signed-off-by: Zander Mackie <zmackie@gmail.com>
=> Document the fact of RFC roundup

ADOPTERS.md
=> Reorder alphabetically, add fly.io

README.md
=> Add working group meetings

ADOPTERS.md
=> Add Paketo to adopters

TEAMS.md
=> Add Jesse Brown as contributor to TEAMS.md

LICENSE
Based on this [policy](https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy), we are changing the license of this repo to "Creative Commons Attribution 4.0 International License".
=> Update LICENSE to CC BY 4.0

contributors/triage.md
Adds a section on how to best write up a "good first issue".
=> Add good-first-issue section

ADOPTERS.md
Project name is "kpack" not "VMware kpack"
=> Fix kpack project name

TEAMS.md
https://lists.cncf.io/g/cncf-buildpacks/topic/team_new_platform/78688481?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,78688481
Signed-off-by: David Freilich <dfreilich@vmware.com>
=> Add dfreilich to Platform Maintainers

TEAMS.md
@ekcasey has asked to step down from the Platform Maintainers team.
=> @ekcasey steps down from Platform Maintainers Team

ADOPTERS.md
> Deploy quickly from 8 major languages via Heroku-compatible Buildpacks... (linked to buildpacks.io)
H/T to @josegonzalez 
cc @ipmb
=> Add AppPack to adopters

VERSIONING.md
=> Replace references to libbuildpack

ROADMAP.md, roadmaps/2020.md
This is the new Cloud Native Buildpacks roadmap for 2021.
=> 2021 Roadmap

GOVERNANCE.md
=> Fix broken and deprecated links

README.md
=> Add details about the office hours and link to the office hours doc

ADOPTERS.md
=> Add Bloomberg to the list of adopters

.github/labels/roadmap.yaml
=> Fix descriptions for roadmap labels

.github/workflows/labels-sync.yaml
List of labels: https://github.com/buildpacks/community/blob/main/.github/labels/roadmap.yaml
Preview
CC: @buildpacks/implementation-maintainers / @buildpacks/core-team
=> Add roadmap labels to more repos

ADOPTERS.md
riff is no more: https://projectriff.io/blog/2021/03/13/goodbye
=> Remove riff

contributors/guide.md
=> Fix working group link

README.md
Also, condensed all other meeting information.
=> Set biweekly sub-team slots

ADOPTERS.md
Signed-off-by: Jose Diaz-Gonzalez <email@josediazgonzalez.com>
=> Add railway.app to ADOPTERS.md

README.md
=> Add share out for CNB Summit 2021

TEAMS.md
=> Add @importhuman to platform project contributors

README.md
=> Switch to CNCF Zoom

TEAMS.md
=> Add Sambhav to BAT maintainers

ADOPTERS.md
Docs here: https://docs.epinio.io/explanations/detailed-push-process.html#6-stage
=> Add Epinio (epinio.io) to the adopters list

GOVERNANCE.md
=> Clarify that contributors are approved by sub team maintainers

TEAMS.md
=> Add Anthony as implementation contributor

TEAMS.md
=> Add @AidanDelaney as a learning team contributor

TEAMS.md
=> Add Forest to the BAT team

TEAMS.md
@buildpacks/platform-maintainers Please vote by approving this PR.
If you have any questions, comments, or concerns, please reach out to me.
=> Add @samj1912 as Platform contributor

GOVERNANCE.md, README.md
Signed-off-by: Emily Casey <ecasey@vmware.com>
=> Governance Clarifications

GOVERNANCE.md
* consistent casing
* typo fix
Signed-off-by: Emily Casey <ecasey@pivotal.io>
=> typographical fixes for governance changes

OWNERS, TEAMS.md
=> Add @AidanDelaney as learning team maintainer and @samj1912 as emeritus

ADOPTERS.md
=> Fix Raildway link

README.md
Previously Team Lead sync
Signed-off-by: Joe Kutner <jpkutner@gmail.com>
=> Rename Leadership sync

TEAMS.md
https://github.com/orgs/buildpacks/teams/toc/discussions/1
=> Set Aidan Delaney as Learning Team Lead

TEAMS.md
=> Add @gcemaj to BAT contributors

README.md
=> Removes office hours

README.md
These meetings haven't happened in awhile...
=> Remove platform and implementation syncs

TEAMS.md
=> Thank you Emily

GOVERNANCE.md, TEAMS.md
https://github.com/buildpacks/rfcs/blob/main/text/0114-distribution-team-merge-platform.md
=> Implement RFC-0114: Merge Distribution and Platform

ADOPTERS.md
Fixes #207 
Signed-off-by: Juan Bustamante <jbustamante@vmware.com>
=> Fixing broken link to create a pull request in the Adpoters page

TEAMS.md
Adds Joe as implementation contributor and moves some folks to emeritus
=> Update implementation contributors

TEAMS.md
=> move juan to platform maintainer

TEAMS.md
@edmorley this is first step in becoming a component maintainer.
=> Add edmorley as platform contrib

TEAMS.md
For https://github.com/buildpacks/github-actions
=> Add @edmorley as component maintainer
